/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Airport: typeof import('./src/components/flyht/list/filter/airport/index.vue')['default']
    Date: typeof import('./src/components/flyht/list/filter/date/index.vue')['default']
    Filter: typeof import('./src/components/flyht/list/filter/index.vue')['default']
    Flyed: typeof import('./src/components/flyed/index.vue')['default']
    Flyht: typeof import('./src/components/flyht/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Item: typeof import('./src/components/flyht/item/index.vue')['default']
    List: typeof import('./src/components/flyht/list/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sort: typeof import('./src/components/flyht/list/sort/index.vue')['default']
  }
}
